# DETERMINAN

Asumsikan A adalah suatu matriks bujur sangkar, fungsi
determinan, det(A) adalah jumlah semua hasil kali dasar
bertanda dari A. atau Determinan ordo n ialah suatu skalar yang terkait dengan
sebuah matriks bujur sangkar A yang berordo n.

## MINOR & KOFAKTOR DETERMINAN

- Jika A adalah suatu matriks bujur sangkar, maka Minor
elemen aij (Mij) didefinisikan sebagai determinan submatriks yang masih tersisa setelah baris ke-i dan kolomke-j dihilangkan
- Kofaktor elemen aij dinyatakan sebagai $k_{ij} = (-1)^{i+j} M_{ij}$

## SIFAT-SIFAT DETERMINAN

- det(A) = 0 jika dalam suatu baris/kolom semua elemennya
nol
- det(A) = det(AT)
- Nilai determinan menjadi k kali bila dalam satu
baris/kolom dikalikan dengan k (suatu skala).
- det(A) = 0 jika 2 baris/kolom sebanding.
-  Nilai determinan berubah tanda jika dua baris/kolomditukar tempatnya
- Nilai determinan tidak berubah jika baris/kolom ke – i
ditambah k kali baris/kolom ke – j.
- Elemen sebuah baris/kolom memuat 2 buah suku maka
determinan tersebut dapat ditulis sebagai jumlah
determinan.

## Contoh

Buat 2 matriks dengan nama A = 2x2 dan B = 3x3

In [1]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
A = np.array([[2,3],[3,1]])
B = np.array([[2,1,3],[1,1,3],[3,2,2]])
C = np.array([[1,0],[0,1]])
D = np.array([[1,0,0],[0,1,0],[0,0,1]])

print(A)
print(B)
print(C)
print(D)

[[2 3]
 [3 1]]
[[2 1 3]
 [1 1 3]
 [3 2 2]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Determinan dari sebuah matriks identitas =

In [3]:
E = np.linalg.det(C)
F = np.linalg.det(D)
a = np.linalg.det(A)
b = np.linalg.det(B)

print(E)
print(F)
print(a)
print(b)

1.0
1.0
-7.000000000000001
-4.0


In [4]:
c = a * (1/2*a)
print(c.round())

25.0


mencari invers matriks A

In [5]:
G = np.linalg.inv(A)
H = np.linalg.inv(B)

print(G)
print(H)

[[-0.14285714  0.42857143]
 [ 0.42857143 -0.28571429]]
[[ 1.   -1.    0.  ]
 [-1.75  1.25  0.75]
 [ 0.25  0.25 -0.25]]


determinan i = det a . det a invers

In [6]:
I = np.linalg.det(G)
J = np.linalg.det(H)

print(I)
print(J)

-0.1428571428571428
-0.24999999999999994


- Sifat yang kedua misalkan ab
- det ab = det a . det b
- i = a. a invers
- det i = det a . det a invers
- det a invers = 1/ det a

In [7]:
e = np.array([[3,5,1],[2,6,2],[1,3,1]])
f = np.array([[1,1,2],[1,1,3],[2,1,2]])

print(e)
print(f)

[[3 5 1]
 [2 6 2]
 [1 3 1]]
[[1 1 2]
 [1 1 3]
 [2 1 2]]


In [8]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [9]:
a = np.linalg.det(A)

print(a.round())

5.0


merubah baris darisebuah matriks akan merubah sebuah tanda dari determinan

In [10]:
A1 = np.array([[1,1,1],[1,4,2],[3,2,1]])

print(A1)

[[1 1 1]
 [1 4 2]
 [3 2 1]]


In [11]:
a = np.linalg.det(A1)

print(a.round())

-5.0


merubah kolom pada matriks

In [12]:
A = np.array([[4,1,2],[1,1,1],[2,3,1]])

print(A)

[[4 1 2]
 [1 1 1]
 [2 3 1]]


In [13]:
a = np.linalg.det(A)

print(a.round())

-5.0


Penjelasan :

- jika baris dari matrik merupakan kelipatan dari baris yang lain maka nilai matriks determinan yang ada sama dengan 0
- kelipatan baris matriknya adalah 2 kali matriks awal

In [14]:
A = np.array([[1,4,2],[2,8,4],[3,2,1]])

print(A)

[[1 4 2]
 [2 8 4]
 [3 2 1]]


In [15]:
a = np.linalg.det(A)

print(a.round())

0.0


Penjelasan :

- jika kolom dari sebuah matriks adalah kelipatan dari kolom yang lainnya maka determinan matriks yang dicari adalah 0
- kolom kedua adalah kelipatan dari kolom pertama atau kolom yang lain

In [16]:
B = np.array([[1,4,2],[2,8,3],[1,4,1]])

print(B)

[[1 4 2]
 [2 8 3]
 [1 4 1]]


In [17]:
b = np.linalg.det(B)

print(b.round())

0.0


- k = skala
- A = matriks nxn
- det k.A = K pangkat n dikali det A

In [18]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [19]:
a = np.linalg.det(A)

print(a.round())

5.0


In [20]:
KA = np.array([[2,8,4],[2,2,2],[6,4,2]])

print(KA)

[[2 8 4]
 [2 2 2]
 [6 4 2]]


det (KA) = 2 pangkat 3 . 5 = 40

In [21]:
b = np.linalg.det(KA)

print(b.round())

40.0


In [22]:
B = np.array([[2,8,4],[1,1,1],[3,2,1]])

print(B)

[[2 8 4]
 [1 1 1]
 [3 2 1]]


- = 2*Det A

- maka dengan t adalah skala
- maka det(b) = t kali dengan Det (A)

In [23]:
b = np.linalg.det(B)

print(b.round())

10.0


- Matriks segitiga atas
dimana d bawah diagonal elemennya nol
-  matriks segitiga bawah
dimana diatas diagonal elemennya nol
- det matrik segitiga adalah
det A = d1 kali d2 sampai dn
- perkalian pada setiap elemen diagonal matriksnya

In [24]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])

print(A)

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]]


det (A) = 2.1.5.3 = 30

In [25]:
a = np.linalg.det(A)

print(a.round())

30.0


Merubah nilai baris tidak merubah nilai determinan dari suatu matriks

In [26]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [27]:
a = np.linalg.det(A)

print(a.round())

5.0


In [28]:
B = np.array([[1,4,2],[0,-3,-1],[3,2,1]])

print(B)

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]]


In [29]:
b = np.linalg.det(B)

print(b.round())

5.0


det A transpose = det A

In [30]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [31]:
A1 = np.transpose(A)

print(A1)

[[1 1 3]
 [4 1 2]
 [2 1 1]]


In [32]:
a = np.linalg.det(A1)

print(a.round())

5.0


## EKSPANSI KOFAKTOR
adalah salah satu metode mencari determinan suatu matriks, di mana dalam metode ini memanfaatkan kofaktor. Pencarian determinan menggunakan metode ini tidak terbatas dengan satu ukuran matriks. Dengan kata lain, dapat dihitung matriks 3x3, 4x4, 5x5, dan seterusnya.

In [33]:
a = np.array([[3,1,2,4],[2,1,1,1],[3,4,2,1],[3,2,1,3]])

print(a)

[[3 1 2 4]
 [2 1 1 1]
 [3 4 2 1]
 [3 2 1 3]]


In [34]:
b = np.linalg.det(a)

print(b.round())

12.0


## CONTOH PENYELESAIAN MATRIKS DETERMINAN DENGAN METODE EKSPANSI KONFAKTOR

Menggunakan Matriks 4X4 sebagai berikut :

$ A = \begin{pmatrix}
3 & 1 & 2 & 4 \\
2 & 1 & 1 & 1 \\
3 & 4 & 1 & 1 \\
3 & 2 & 1 & 3 \\
\end{pmatrix} $

**Rumus Penurunan Kofaktor dengan cara menangani ekspansi kofaktor 3×3 . Kita ambil submatriks kedua di atas dan dilambangkan dengan M :**
- A21 C21 = $(-1)^{2+1}(det M21)$
- A22 C22 = $(-1)^{2+2}(det M22)$
- A23 C23 = $(-1)^{2+3}(det M23)$
- A24 C24 = $(-1)^{2+4}(det M24)$

Dimana :

$ M21 = \begin{pmatrix}
1 & 2 & 4 \\
4 & 2 & 1 \\
2 & 1 & 3 \\
\end{pmatrix}
M22 = \begin{pmatrix}
3 & 2 & 4 \\
3 & 2 & 1 \\
3 & 1 & 3 \\
\end{pmatrix} $

$M23 = \begin{pmatrix}
3 & 1 & 4 \\
3 & 4 & 1 \\
3 & 2 & 3 \\
\end{pmatrix}
M24 = \begin{pmatrix}
3 & 1 & 2 \\
3 & 4 & 2 \\
3 & 2 & 1 \\
\end{pmatrix} $

**Hitung menangani Setiap ekspansi Kofaktor 2X2 dari M21. Kita ambil submatriks kedua di atas dan dilambangkan dengan detM :**
- A11 C11 = $(-1)^{1+1}(det M11)$
- A12 C12 = $(-1)^{1+2}(det M12)$
- A13 C13 = $(-1)^{1+3}(det M13)$

Dimana Det:

$ M11 = \begin{pmatrix}
2 & 1 \\
1 & 3 \\
\end{pmatrix}
M12 = \begin{pmatrix}
4 & 1 \\
2 & 3 \\
\end{pmatrix}
M13 = \begin{pmatrix}
4 & 2 \\
2 & 1 \\
\end{pmatrix} $

Oleh Karena Itu :
- M11 = $(-1)^{1+1}((2*3)-(1*1)) = (-1)^{1+1}(6-1) = 1*1*5 = 5 $
- M12 = $(-1)^{1+2}((4*3)-(1*2)) = (-1)^{1+2}(12-2) = -1*2*10 = -20 $
- M13 = $(-1)^{1+3}((4*1)-(2*2)) = (-1)^{1+3}(4-4) = 1*3*0 = 0 $

Akhir yang diperoleh :
det(A) = 5 + -20 + 0 = -15

**Hitung menangani Setiap ekspansi Kofaktor 2X2 dari M22. Kita ambil submatriks kedua di atas dan dilambangkan dengan detM :**
- A11 C11 = $(-1)^{1+1}(det M11)$
- A12 C12 = $(-1)^{1+2}(det M12)$
- A13 C13 = $(-1)^{1+3}(det M13)$

Dimana Det:

$ M11 = \begin{pmatrix}
2 & 1 \\
1 & 3 \\
\end{pmatrix}
M12 = \begin{pmatrix}
3 & 1 \\
3 & 3 \\
\end{pmatrix}
M13 = \begin{pmatrix}
3 & 2 \\
3 & 1 \\
\end{pmatrix} $

Oleh Karena Itu :
- M11 = $(-1)^{1+1}((2*3)-(1*1)) = (-1)^{1+1}(6-1) = 1*3*5 = 15 $
- M12 = $(-1)^{1+2}((3*3)-(1*3)) = (-1)^{1+2}(9-3) = -1*2*6 = -12 $
- M13 = $(-1)^{1+3}((3*1)-(3*2)) = (-1)^{1+3}(3-6) = 1*4*-3 = -12 $

Akhir yang diperoleh :
det(A) = 15 + -12 + -12 = -9

**Hitung menangani Setiap ekspansi Kofaktor 2X2 dari M23. Kita ambil submatriks kedua di atas dan dilambangkan dengan detM :**
- A11 C11 = $(-1)^{1+1}(det M11)$
- A12 C12 = $(-1)^{1+2}(det M12)$
- A13 C13 = $(-1)^{1+3}(det M13)$

Dimana Det:

$ M11 = \begin{pmatrix}
4 & 1 \\
2 & 3 \\
\end{pmatrix}
M12 = \begin{pmatrix}
3 & 1 \\
3 & 3 \\
\end{pmatrix}
M13 = \begin{pmatrix}
3 & 4 \\
3 & 2 \\
\end{pmatrix} $

Oleh Karena Itu :
- M11 = $(-1)^{1+1}((4*3)-(1*2)) = (-1)^{1+1}(12-2) = 1*3*10 = 30 $
- M12 = $(-1)^{1+2}((3*3)-(1*3)) = (-1)^{1+2}(9-3) = -1*1*6 = -6 $
- M13 = $(-1)^{1+3}((3*2)-(4*3)) = (-1)^{1+3}(6-12) = 1*4*-6 = -24 $

Akhir yang diperoleh :
det(A) = 30 + -6 + -24 = 0

**Hitung menangani Setiap ekspansi Kofaktor 2X2 dari M24. Kita ambil submatriks kedua di atas dan dilambangkan dengan detM :**
- A11 C11 = $(-1)^{1+1}(det M11)$
- A12 C12 = $(-1)^{1+2}(det M12)$
- A13 C13 = $(-1)^{1+3}(det M13)$

Dimana Det:

$ M11 = \begin{pmatrix}
4 & 2 \\
2 & 1 \\
\end{pmatrix}
M12 = \begin{pmatrix}
3 & 2 \\
3 & 1 \\
\end{pmatrix}
M13 = \begin{pmatrix}
3 & 4 \\
3 & 2 \\
\end{pmatrix} $

Oleh Karena Itu :
- M11 = $(-1)^{1+1}((4*1)-(2*2)) = (-1)^{1+1}(4-4) = 1*3*0 = 0 $
- M12 = $(-1)^{1+2}((3*1)-(2*3)) = (-1)^{1+2}(3-6) = -1*1*-3 = 3 $
- M13 = $(-1)^{1+3}((3*2)-(4*3)) = (-1)^{1+3}(6-12) = 1*2*-6 = -12 $

Akhir yang diperoleh :
det(A) = 0 + 3 + -12 = -9

Oleh karena itu:
- (-1) 2+1 * A 21 * C 2 1 = -1 * 2 * -15 = 30
- (-1) 2+2 * A 22 * ​C 2 2 = 1 * 1 * -9 = -9
- (-1) 2+3 * A 23 * C 2 3 = -1 * 1 * 0 = 0
- (-1) 2+4 * A 24 * C 2 4 = 1 * 1 * -9 = -9

Akhirnya, kita memperoleh:
det(A) = 30 + -9 + 0 + -9 = 12