# EIGEN VALUE & EIGEN VECTOR

**Definisi** 

Jika A adalah $nxn$ maka vektor tidak nol $x$ dinamakan vektor eigen dari A nika $Ax$ adalah kelipan skalar dari X yakni   
  
Ax = $ \lambda X$  
  
Skalar $\lambda$ dinamakan nilai eigen dari A dan x dikatakan vektor eigen yang bersesuaian dengan $\lambda$

Adapun syarat bahwa eigen vektor adalah taknol diberlakukan untuk menghindari kasus yang tidak penting seperti A0 = $\lambda 0$, yang mana berlaku untuk setiap A dan $\lambda$

Ax = λx  
Ax: vektor x setelah transformasi linier  
λx: perkalian bilangan riel dari x, i.e. peregangan dari vektor x.
Transformasi linier untuk eigenvector menghasilkan peregangan vektor
sebanyak eigenvalue kali.  

**Contoh**  
  
Hitung eigen value dan eigen vector dari matrik A  
  
$$
\begin{matrix}
    A = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
\end{matrix}
$$

solusi:  

$
\begin{matrix}
    A - \lambda = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \lambda \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \begin{bmatrix}
        \lambda & 0 \\
        0 & \lambda \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 - \lambda & 5 \\
        4 & 2 - \lambda \\
    \end{bmatrix}
\end{matrix}
$

$
det(A - \lambda) = (3 - \lambda) (2 - \lambda) - 20 \\ 
$  

$
\qquad \qquad \quad = \lambda^2 + 6 - 2 \lambda - 3 \lambda - 20 \\
$  

$
\qquad \qquad \quad = \lambda^2 - 5 \lambda - 14
$  


$
\lambda^2 - 5 \lambda - 14 = 0 \\
$  
$
(\lambda - 7) (\lambda + 2) = 0 \\
$  
$
\lambda = 7 \space dan \space -2 
$  

$Ax = 7x \space dan \space Ax = -2x$  
  
Untuk $\lambda = -2$  
  
$
A - (-2)! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    +
    2 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        5 & 5 \\
        4 & 4 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di peroleh persamaan berikut

$x1 + x2 = 0$  
$x1 = -x2$  
$1.1 = -1.-1$  
$x1 = 1$  
$x2 = -1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1 \\
        -1
    \end{bmatrix}
    = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$  
  
untuk $\lambda = 7$  

$  
A - 7! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    7 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  
    
$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        -4 & 5 \\
        4 & -5 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di dapatkan persamaan:
$-4x1 + 5x2 = 0$  
$5x2 = 4x1$  
$x1 = 1.25$  
$x2 = 1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1.25 \\
        1
    \end{bmatrix}
    = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$  


eignvalue = [7, -2]  
eignvector = [[1,1], [1,-1]]
  
untuk $\lambda = $ 7 dan $x =$ [1,1]  
   
$
\begin{matrix}
    A x = \begin{bmatrix}
       8.75 \\
       7   
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$

untuk $\lambda = $ -2 dan $x =$ [1,-1]  
  

$
\begin{matrix}
    A x = \begin{bmatrix}
       -2 \\
        2  
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$



Menghitung eignvalue dan eignvector dengan numpy

In [1]:
# Menghitung eigenvalue dan eigenvector dengan numpy


# matrixs ukuran 2x2
import numpy as np

A = np.array([[3,5], [4,2]])
eign = np.linalg.eig(A)

print("eignvalue: ", eign[0])
print("eignevector: ", eign[1].round())

# matriks ukuran 3 x 3

B = np.array([[2,3,4], [2,4,3], [4,3,2]])
eign2 = np.linalg.eig(B)

print("eignvalue: ", eign2[0])
print("eignvector: ", eign2[1].round())

print()

eignvalue:  [ 7. -2.]
eignevector:  [[ 1. -1.]
 [ 1.  1.]]
eignvalue:  [ 9. -2.  1.]
eignvector:  [[-1. -1.  0.]
 [-1. -0. -1.]
 [-1.  1.  0.]]



Implementasi eignvalue dan eignvector

In [2]:
import numpy as np


def pcaSVD(matriks):
    row, col = matriks.shape

    matriks_ = matriks - matriks.mean(axis=0)
    u, sigma, vt = np.linalg.svd(matriks_, full_matrices=False)

    
    return ((matriks_ @ vt.T), sigma**2 / (row - 1))

matriks = np.array([[3,5], [4,2]])

eignVector, eignValue = pcaSVD(matriks)
print(eignValue)
print(eignVector.round())

[5. 0.]
[[-2.  0.]
 [ 2. -0.]]


## Mencari nilai eigen value dan eigen vector pada matriks 2x2 menggunakan numpy

In [3]:
import numpy as np
from numpy.linalg import eig

# Matriks 2x2
A = np.array([[1,4],[2,3]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w, '\n')
print('E-value', v.round(), '\n')

[[1 4]
 [2 3]] 

E-value [-1.  5.] 

E-value [[-1. -1.]
 [ 0. -1.]] 



## Mencari nilai eigen value dan eigen vector pada matriks 3x3 menggunakan numpy

In [4]:
import numpy as np
from numpy.linalg import eig

# Matriks 3x3
A = np.array([[1,4,1],[2,3,2],[2,4,5]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w.round(), '\n')
print('E-value', v.round(), '\n')

[[1 4 1]
 [2 3 2]
 [2 4 5]] 

E-value [ 8. -1.  2.] 

E-value [[-0. -1. -1.]
 [-0.  0. -0.]
 [-1.  0.  1.]] 



## Contoh Implementasi Eigenvalue dan Eigenvector

In [5]:
import numpy as np

def pcaEVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)
    C = (X_centered.T @ X_centered) / (n - 1)
    e_vals, e_vecs = np.linalg.eig(C)

    idx = e_vals.argsort()[::-1]
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]

    return (X_centered @ e_vecs), e_vals, e_vecs

X = np.array([[3, 2],
              [2, 3]])

components, eigenvalues, eigenvectors = pcaEVD(X)

rounded_components = np.round(components)
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)
print("Eigenvectors:\n", rounded_eigenvectors)

Components:
 [[ 1. -0.]
 [-1.  0.]]
Eigenvalues:
 [1. 0.]
Eigenvectors:
 [[ 1.  1.]
 [-1.  1.]]
