# SOAL UTS

Mencari matriks invers 2X2 menggunakan RowAdd dan RowScale

In [1]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
A = np.array([[2,3,1,0],[3,1,0,1]])
print(A)

[[2 3 1 0]
 [3 1 0 1]]


In [3]:
A1 = RowScale(A,0,1/2)
print(A1)

[[1.  1.5 0.5 0. ]
 [3.  1.  0.  1. ]]


In [4]:
A2 = RowAdd(A1,0,1, -3)
print(A2)

[[ 1.   1.5  0.5  0. ]
 [ 0.  -3.5 -1.5  1. ]]


In [5]:
A3 = RowScale(A2,1,-1/3.5)
print(A3)

[[ 1.          1.5         0.5         0.        ]
 [-0.          1.          0.42857143 -0.28571429]]


In [6]:
A4 = RowAdd(A3,1,0, -1.5)
print(A4)

[[ 1.          0.         -0.14285714  0.42857143]
 [-0.          1.          0.42857143 -0.28571429]]


In [7]:
b = A4[:,2]
c = A4[:,3]
a = np.column_stack((b,c))

print(a)

[[-0.14285714  0.42857143]
 [ 0.42857143 -0.28571429]]


In [8]:
d = A[:,0]
e = A[:,1]
f = np.column_stack((d,e))

print(f)

[[2 3]
 [3 1]]


In [9]:
g = a @ f
print(g.round())

[[1. 0.]
 [0. 1.]]
